<a href="https://colab.research.google.com/github/GresiaARS/SuperStoreOrder_DataOperation/blob/main/Homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
url = "https://drive.google.com/file/d/1HhOnZXyXkagtgd5TfzM61HPRuuykJ5AN/view?usp=sharing"
url='https://drive.google.com/uc?id=' + url.split('/')[-2]

In [ ]:
df = pd.read_csv(url)

In [ ]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,Unnamed: 66
0,Africa Eastern and Southern,AFE,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,140.120535,140.594564,141.128109,141.32344,141.50816,141.668896,...,103.391461,101.541782,99.719799,97.916601,96.146492,94.695223,93.231944,NaN,NaN,NaN
1,Africa Eastern and Southern,AFE,Adults (ages 15+) and children (0-14 years) li...,SH.HIV.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Africa Eastern and Southern,AFE,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Africa Eastern and Southern,AFE,Adults (ages 15+) living with HIV,SH.DYN.AIDS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Africa Eastern and Southern,AFE,Adults (ages 15-49) newly infected with HIV,SH.HIV.INCD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 117306 entries, 0 to 117305
Data columns (total 67 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Country Name    117306 non-null  object
 1   Country Code    117306 non-null  object
 2   Indicator Name  117306 non-null  object
 3   Indicator Code  117306 non-null  object
 4   1960            37753 non-null   float64
 5   1961            38305 non-null   float64
 6   1962            38880 non-null   float64
 7   1963            38440 non-null   float64
 8   1964            38490 non-null   float64
 9   1965            38651 non-null   float64
 10  1966            38595 non-null   float64
 11  1967            39119 non-null   float64
 12  1968            38709 non-null   float64
 13  1969            38792 non-null   float64
 14  1970            40158 non-null   float64
 15  1971            40895 non-null   float64
 16  1972            41437 non-null   float64
 17  1973            40988 non-null   float64
 18  1974            41028 non-null   float64
 19  1975            41997 non-null   float64
 20  1976            42075 non-null   float64
 21  1977            42567 non-null   float64
 22  1978            42141 non-null   float64
 23  1979            42228 non-null   float64
 24  1980            43058 non-null   float64
 25  1981            43343 non-null   float64
 26  1982            43631 non-null   float64
 27  1983            43248 non-null   float64
 28  1984            43473 non-null   float64
 29  1985            43742 non-null   float64
 30  1986            44128 non-null   float64
 31  1987            44593 non-null   float64
 32  1988            43945 non-null   float64
 33  1989            44197 non-null   float64
 34  1990            52295 non-null   float64
 35  1991            52730 non-null   float64
 36  1992            53407 non-null   float64
 37  1993            52845 non-null   float64
 38  1994            52801 non-null   float64
 39  1995            53093 non-null   float64
 40  1996            53289 non-null   float64
 41  1997            53459 non-null   float64
 42  1998            53237 non-null   float64
 43  1999            54317 non-null   float64
 44  2000            71764 non-null   float64
 45  2001            68718 non-null   float64
 46  2002            69457 non-null   float64
 47  2003            69261 non-null   float64
 48  2004            69774 non-null   float64
 49  2005            71387 non-null   float64
 50  2006            70778 non-null   float64
 51  2007            71404 non-null   float64
 52  2008            70457 non-null   float64
 53  2009            70973 non-null   float64
 54  2010            75273 non-null   float64
 55  2011            71916 non-null   float64
 56  2012            72349 non-null   float64
 57  2013            71108 non-null   float64
 58  2014            72429 non-null   float64
 59  2015            73050 non-null   float64
 60  2016            72903 non-null   float64
 61  2017            71956 non-null   float64
 62  2018            71383 non-null   float64
 63  2019            67066 non-null   float64
 64  2020            50967 non-null   float64
 65  2021            1053 non-null    float64
 66  Unnamed: 66     0 non-null       float64
dtypes: float64(63), object(4)
memory usage: 60.0+ MB

In [ ]:
df['Indicator Name'].unique()

array(['Adolescent fertility rate (births per 1,000 women ages 15-19)',
       'Adults (ages 15+) and children (0-14 years) living with HIV',
       'Adults (ages 15+) and children (ages 0-14) newly infected with HIV',
       'Adults (ages 15+) living with HIV',
       'Adults (ages 15-49) newly infected with HIV',
       'Age at first marriage, female', 'Age at first marriage, male',
       'Age dependency ratio (% of working-age population)',
       'Age dependency ratio, old', 'Age dependency ratio, young',
       'Age population, age 00, female, interpolated',
       'Age population, age 00, male, interpolated',
       'Age population, age 01, female, interpolated',
       'Age population, age 01, male, interpolated',
       'Age population, age 02, female, interpolated',
       'Age population, age 02, male, interpolated',
       'Age population, age 03, female, interpolated',
       'Age population, age 03, male, interpolated',
       'Age population, age 04, female, interpolated',
       'Age population, age 04, male, interpolated',
       'Age population, age 05, female, interpolated',
       'Age population, age 05, male, interpolated',
       'Age population, age 06, female, interpolated',
       'Age population, age 06, male, interpolated',
       'Age population, age 07, female, interpolated',
       'Age population, age 07, male, interpolated',
       'Age population, age 08, female, interpolated',
       'Age population, age 08, male, interpolated',
       'Age population, age 09, female, interpolated',
       'Age population, age 09, male, interpolated',
       'Age population, age 10, female, interpolated',
       'Age population, age 10, male, interpolated',
       'Age population, age 11, female, interpolated',
       'Age population, age 11, male, interpolated',
       'Age population, age 12, female, interpolated',
       'Age population, age 12, male, interpolated',
       'Age population, age 13, female, interpolated',
       'Age population, age 13, male, interpolated',
       'Age population, age 14, female, interpolated',
       'Age population, age 14, male, interpolated',
       'Age population, age 15, female, interpolated',
       'Age population, age 15, male, interpolated',
       'Age population, age 16, female, interpolated',
       'Age population, age 16, male, interpolated',
       'Age population, age 17, female, interpolated',
       'Age population, age 17, male, interpolated',
       'Age population, age 18, female, interpolated',
       'Age population, age 18, male, interpolated',
       'Age population, age 19, female, interpolated',
       'Age population, age 19, male, interpolated',
       'Age population, age 20, female, interpolated',
       'Age population, age 20, male, interpolated',
       'Age population, age 21, female, interpolated',
       'Age population, age 21, male, interpolated',
       'Age population, age 22, female, interpolated',
       'Age population, age 22, male, interpolated',
       'Age population, age 23, female, interpolated',
       'Age population, age 23, male, interpolated',
       'Age population, age 24, female, interpolated',
       'Age population, age 24, male, interpolated',
       'Age population, age 25, female, interpolated',
       'Age population, age 25, male, interpolated',
       'AIDS estimated deaths (UNAIDS estimates)',
       'Antiretroviral therapy coverage (% of people living with HIV)',
       'Antiretroviral therapy coverage for PMTCT (% of pregnant women living with HIV)',
       'ARI treatment (% of children under 5 taken to a health provider)',
       'Birth rate, crude (per 1,000 people)',
       'Births attended by skilled health staff (% of total)',
       'Capital health expenditure (% of GDP)',
       'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
       'Cause of death, by injury (% of total)',
       'Cause of death, by non-communicable diseases (% of total)',
       'Children (0-14) living with HIV',
       'Children (ages 0-14) newly infected with HIV',
       'Children orphaned by HIV/AIDS',
       'Children with fever receiving antimalarial drugs (% of children under age 5 with fever)',
       'Community health workers (per 1,000 people)',
       'Completeness of birth registration (%)',
       'Completeness of birth registration, female (%)',
       'Completeness of birth registration, male (%)',
       'Completeness of birth registration, rural (%)',
       'Completeness of birth registration, urban (%)',
       'Completeness of death registration with cause-of-death information (%)',
       'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, female (2 prevent ways and reject 3 misconceptions)',
       'Comprehensive correct knowledge of HIV/AIDS, ages 15-24, male (2 prevent ways and reject 3 misconceptions)',
       'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, female (2 prevent ways and reject 3 misconceptions)',
       'Comprehensive correct knowledge of HIV/AIDS, ages 15-49, male (2 prevent ways and reject 3 misconceptions)',
       'Condom use at last high-risk sex, adult female (% ages 15-49)',
       'Condom use at last high-risk sex, adult male (% ages 15-49)',
       'Condom use, population ages 15-24, female (% of females ages 15-24)',
       'Condom use, population ages 15-24, male (% of males ages 15-24)',
       'Consumption of iodized salt (% of households)',
       'Contraceptive prevalence, any method (% of married women ages 15-49)',
       'Contraceptive prevalence, any method (% of sexually active unmarried women ages 15-49)',
       'Contraceptive prevalence, any modern method (% of married women ages 15-49)',
       'Contraceptive prevalence, any modern method (% of sexually active unmarried women ages 15-49)',
       'Current health expenditure (% of GDP)',
       'Current health expenditure per capita (current US$)',
       'Current health expenditure per capita, PPP (current international $)',
       'Death rate, crude (per 1,000 people)',
       'Demand for family planning satisfied by any methods (% of married women with demand for family planning)',
       'Demand for family planning satisfied by modern methods (% of married women with demand for family planning)',
       'Diabetes prevalence (% of population ages 20 to 79)',
       'Diarrhea treatment (% of children under 5 receiving oral rehydration and continued feeding)',
       'Diarrhea treatment (% of children under 5 who received ORS packet)',
       'Domestic general government health expenditure (% of current health expenditure)',
       'Domestic general government health expenditure (% of GDP)',
       'Domestic general government health expenditure (% of general government expenditure)',
       'Domestic general government health expenditure per capita (current US$)',
       'Domestic general government health expenditure per capita, PPP (current international $)',
       'Domestic private health expenditure (% of current health expenditure)',
       'Domestic private health expenditure per capita (current US$)',
       'Domestic private health expenditure per capita, PPP  (current international $)',
       'Exclusive breastfeeding (% of children under 6 months)',
       'External health expenditure (% of current health expenditure)',
       'External health expenditure channeled through government (% of external health expenditure)',
       'External health expenditure per capita (current US$)',
       'External health expenditure per capita, PPP (current international $)',
       'Female headed households (% of households with a female head)',
       'Fertility rate, total (births per woman)',
       'GNI per capita, Atlas method (current US$)',
       'Hospital beds (per 1,000 people)',
       'Human capital index (HCI) (scale 0-1)',
       'Human capital index (HCI), female (scale 0-1)',
       'Human capital index (HCI), female, lower bound (scale 0-1)',
       'Human capital index (HCI), female, upper bound (scale 0-1)',
       'Human capital index (HCI), lower bound (scale 0-1)',
       'Human capital index (HCI), male (scale 0-1)',
       'Human capital index (HCI), male, lower bound (scale 0-1)',
       'Human capital index (HCI), male, upper bound (scale 0-1)',
       'Human capital index (HCI), upper bound (scale 0-1)',
       'Immunization, BCG (% of one-year-old children)',
       'Immunization, DPT (% of children ages 12-23 months)',
       'Immunization, HepB3 (% of one-year-old children)',
       'Immunization, Hib3 (% of children ages 12-23 months)',
       'Immunization, measles (% of children ages 12-23 months)',
       'Immunization, measles second dose (% of children by the nationally recommended age)',
       'Immunization, Pol3 (% of one-year-old children)',
       'Incidence of HIV, ages 15-24 (per 1,000 uninfected population ages 15-24)',
       'Incidence of HIV, ages 15-49 (per 1,000 uninfected population ages 15-49)',
       'Incidence of HIV, ages 50+ (per 1,000 uninfected population ages 50+)',
       'Incidence of HIV, all (per 1,000 uninfected population)',
       'Incidence of malaria (per 1,000 population at risk)',
       'Incidence of tuberculosis (per 100,000 people)',
       'Infant and young child feeding practices, all 3 IYCF (% children ages 6-23 months)',
       'Intermittent preventive treatment (IPT) of malaria in pregnancy (% of pregnant women)',
       'Labor force, female (% of total labor force)',
       'Labor force, total', 'Life expectancy at birth, female (years)',
       'Life expectancy at birth, male (years)',
       'Life expectancy at birth, total (years)',
       'Lifetime risk of maternal death (%)',
       'Lifetime risk of maternal death (1 in: rate varies by country)',
       'Literacy rate, adult female (% of females ages 15 and above)',
       'Literacy rate, adult male (% of males ages 15 and above)',
       'Literacy rate, adult total (% of people ages 15 and above)',
       'Literacy rate, youth male (% of males ages 15-24)',
       'Literacy rate, youth total (% of people ages 15-24)',
       'Low-birthweight babies (% of births)', 'Malaria cases reported',
       'Maternal leave benefits (% of wages paid in covered period)',
       'Maternal mortality ratio (modeled estimate, per 100,000 live births)',
       'Maternal mortality ratio (national estimate, per 100,000 live births)',
       'Mortality caused by road traffic injury (per 100,000 people)',
       'Mortality caused by road traffic injury, female (per 100,000 female population)',
       'Mortality caused by road traffic injury, male (per 100,000 male population)',
       'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%)',
       'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)',
       'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, male (%)',
       'Mortality rate attributed to household and ambient air pollution (per 100,000 population)',
       'Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)',
       'Mortality rate attributed to household and ambient air pollution, age-standardized, male (per 100,000 male population)',
       'Mortality rate attributed to unintentional poisoning (per 100,000 population)',
       'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)',
       'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)',
       'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)',
       'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, female (per 100,000 female population)',
       'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, male (per 100,000 male population)',
       'Mortality rate, adult, female (per 1,000 female adults)',
       'Mortality rate, adult, male (per 1,000 male adults)',
       'Mortality rate, infant (per 1,000 live births)',
       'Mortality rate, infant, female (per 1,000 live births)',
       'Mortality rate, infant, male (per 1,000 live births)',
       'Mortality rate, neonatal (per 1,000 live births)',
       'Mortality rate, under-5 (per 1,000)',
       'Mortality rate, under-5, female (per 1,000)',
       'Mortality rate, under-5, male (per 1,000)', 'Net migration',
       'Newborns protected against tetanus (%)',
       'Number of deaths ages 10-14 years',
       'Number of deaths ages 10-19 years',
       'Number of deaths ages 15-19 years',
       'Number of deaths ages 20-24 years',
       'Number of deaths ages 5-9 years', 'Number of infant deaths',
       'Number of infant deaths, female', 'Number of infant deaths, male',
       'Number of maternal deaths', 'Number of neonatal deaths',
       'Number of people pushed below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure',
       'Number of people pushed below the $3.20 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure',
       'Number of people pushed below the 60% median consumption poverty line by out-of-pocket health care expenditure',
       'Number of people pushed further below the $1.90 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure',
       'Number of people pushed further below the $3.20 ($ 2011 PPP) poverty line by out-of-pocket health care expenditure',
       'Number of people pushed further below the 60% median consumption poverty line by out-of-pocket health care expenditure',
       'Number of people spending more than 10% of household consumption or income on out-of-pocket health care expenditure',
       'Number of people spending more than 25% of household consumption or income on out-of-pocket health care expenditure',
       'Number of people who are undernourished', 'Number of stillbirths',
       'Number of surgical procedures (per 100,000 population)',
       'Number of under-five deaths',
       'Number of under-five deaths, female',
       'Number of under-five deaths, male',
       'Nurses and midwives (per 1,000 people)',
       'Out-of-pocket expenditure (% of current health expenditure)',
       'Out-of-pocket expenditure per capita (current US$)',
       'Out-of-pocket expenditure per capita, PPP (current international $)',
       'People practicing open defecation (% of population)',
       'People practicing open defecation, rural (% of rural population)',
       'People practicing open defecation, urban (% of urban population)',
       'People using at least basic drinking water services (% of population)',
       'People using at least basic drinking water services, rural (% of rural population)',
       'People using at least basic drinking water services, urban (% of urban population)',
       'People using at least basic sanitation services (% of population)',
       'People using at least basic sanitation services, rural (% of rural population)',
       'People using at least basic sanitation services, urban  (% of urban population)',
       'People using safely managed drinking water services (% of population)',
       'People using safely managed drinking water services, rural (% of rural population)',
       'People using safely managed drinking water services, urban (% of urban population)',
       'People using safely managed sanitation services (% of population)',
       'People using safely managed sanitation services, rural (% of rural population)',
       'People using safely managed sanitation services, urban  (% of urban population)',
       'People with basic handwashing facilities including soap and water (% of population)',
       'People with basic handwashing facilities including soap and water, rural (% of rural population)',
       'People with basic handwashing facilities including soap and water, urban (% of urban population)',
       'Physicians (per 1,000 people)', 'Population ages 00-04, female',
       'Population ages 00-04, female (% of female population)',
       'Population ages 00-04, male',
       'Population ages 00-04, male (% of male population)',
       'Population ages 00-14, total',
       'Population ages 0-14 (% of total population)',
       'Population ages 0-14, female',
       'Population ages 0-14, female (% of female population)',
       'Population ages 0-14, male',
       'Population ages 0-14, male (% of male population)',
       'Population ages 05-09, female',
       'Population ages 05-09, female (% of female population)',
       'Population ages 05-09, male',
       'Population ages 05-09, male (% of male population)',
       'Population ages 10-14, female',
       'Population ages 10-14, female (% of female population)',
       'Population ages 10-14, male',
       'Population ages 10-14, male (% of male population)',
       'Population ages 15-19, female',
       'Population ages 15-19, female (% of female population)',
       'Population ages 15-19, male',
       'Population ages 15-19, male (% of male population)',
       'Population ages 15-64 (% of total population)',
       'Population ages 15-64, female',
       'Population ages 15-64, female (% of female population)',
       'Population ages 15-64, male',
       'Population ages 15-64, male (% of male population)',
       'Population ages 15-64, total', 'Population ages 20-24, female',
       'Population ages 20-24, female (% of female population)',
       'Population ages 20-24, male',
       'Population ages 20-24, male (% of male population)',
       'Population ages 25-29, female',
       'Population ages 25-29, female (% of female population)',
       'Population ages 25-29, male',
       'Population ages 25-29, male (% of male population)',
       'Population ages 30-34, female',
       'Population ages 30-34, female (% of female population)',
       'Population ages 30-34, male',
       'Population ages 30-34, male (% of male population)',
       'Population ages 35-39, female',
       'Population ages 35-39, female (% of female population)',
       'Population ages 35-39, male',
       'Population ages 35-39, male (% of male population)',
       'Population ages 40-44, female',
       'Population ages 40-44, female (% of female population)',
       'Population ages 40-44, male',
       'Population ages 40-44, male (% of male population)',
       'Population ages 45-49, female',
       'Population ages 45-49, female (% of female population)',
       'Population ages 45-49, male',
       'Population ages 45-49, male (% of male population)',
       'Population ages 50-54, female',
       'Population ages 50-54, female (% of female population)',
       'Population ages 50-54, male',
       'Population ages 50-54, male (% of male population)',
       'Population ages 55-59, female',
       'Population ages 55-59, female (% of female population)',
       'Population ages 55-59, male',
       'Population ages 55-59, male (% of male population)',
       'Population ages 60-64, female',
       'Population ages 60-64, female (% of female population)',
       'Population ages 60-64, male',
       'Population ages 60-64, male (% of male population)',
       'Population ages 65 and above (% of total population)',
       'Population ages 65 and above, female',
       'Population ages 65 and above, female (% of female population)',
       'Population ages 65 and above, male',
       'Population ages 65 and above, male (% of male population)',
       'Population ages 65 and above, total',
       'Population ages 65-69, female',
       'Population ages 65-69, female (% of female population)',
       'Population ages 65-69, male',
       'Population ages 65-69, male (% of male population)',
       'Population ages 70-74, female',
       'Population ages 70-74, female (% of female population)',
       'Population ages 70-74, male',

Which country has the lowest death caused by nutrition in 2019?

In [ ]:
df_death = df[(df['Indicator Name'] == 'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)')]

In [ ]:
df_death =df_death.sort_values(by=['2019'], ascending=True).head(1)

In [ ]:
df_death[['Country Name', '2019']]

          Country Name      2019
85623  North Macedonia  1.283611

Which country has the highest rate of diabetes prevalence in 2021?

In [ ]:
df_diabetes = df[(df['Indicator Name'] == 'Diabetes prevalence (% of population ages 20 to 79)')]

In [ ]:
df_diabetes =df_diabetes.sort_values(by=['2021'], ascending= False).head(1)

In [ ]:
df_diabetes[['Country Name', '2021']]

      Country Name  2021
87420     Pakistan  30.8

How much is the working age population of Mali in 2020?

In [ ]:
df_Mali = df[(df['Indicator Name'] == 'Age dependency ratio (% of working-age population)')]
df_Mali = df_Mali[['Country Name', '2020']]

In [ ]:
df_Mali[df_Mali['Country Name'] == 'Mali']

      Country Name      2020
75418         Mali  97.95885

How many Indonesian adults (age 15+) are living with HIV in 2020?

In [ ]:
df_Indo = df[(df['Indicator Name'] == 'Adults (ages 15+) living with HIV')]

In [ ]:
df_Indo = df_Indo[['Country Name', '2020']]

In [ ]:
df_Indo[df_Indo['Country Name'] == 'Indonesia']

      Country Name      2020
61302    Indonesia  520000.0

Which country has the lowest rate of literacy in 2020?

In [ ]:
df_literacy = df[df['Indicator Name'] == 'Literacy rate, adult total (% of people ages 15 and above)']

In [ ]:
df_literacy = df_literacy.sort_values(by=['2020'], ascending=True).head(1)

In [ ]:
df_literacy[['Country Name', '2020']]

      Country Name      2020
75566         Mali  30.76141